### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'time'

### ISSUE THREAD

**Issue by Autumn-27** [lakemoon602/snail2.0#1]
Traceback (most recent call last):
  File "snail.py", line 214, in <module>
    timeout=int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'time'

**Comment by lakemoon602** [comment]
更新了readme,是我没把用法解释清楚....
python snail.py domain.txt 0
第二个参数是必须的，代表延时，一般1或者2就能防止被ban,大部分网站0就可以了
